routes/web.php
<?php

use App\Http\Controllers\ConfigurationController;
use App\Http\Controllers\FeedNewsListController;
use App\Http\Controllers\FeedReaderController;
use App\Http\Controllers\FeedWppAdiFeedController;
use App\Http\Controllers\NewsListController;
use App\Http\Controllers\NewspaperController;
use App\Http\Controllers\NewspaperTagurlController;
use App\Http\Controllers\ProfileController;
use App\Http\Controllers\TagController;
use App\Http\Controllers\WppAdiFeedController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

// Route::get('/', function () {
//     return view('welcome');
// });

Route::get('/', function () {
    return view('dashboard');
})->middleware(['auth', 'verified'])->name('dashboard');
Route::get('/dashboard', function () {
    return view('dashboard');
})->middleware(['auth', 'verified'])->name('dashboard');

Route::get('/feed-reader', [FeedReaderController::class, 'index']);
Route::get('/feed-update-news-stats', [FeedReaderController::class, 'updateNewsStats']);

Route::get('/feed-reader', [FeedReaderController::class, 'index']);
Route::post('/feed-wp-ativar', [FeedWppAdiFeedController::class, 'wpActive']);
Route::get('/wp-active-all-domain', [FeedWppAdiFeedController::class, 'wpActiveAllDomain']);
Route::get('/feed-job', [FeedWppAdiFeedController::class, 'index']);
Route::get('/feed-direct-url', [FeedWppAdiFeedController::class, 'feedDirectUrl']);

Route::get('/feed-wp-adi-plugin-update', [WppAdiFeedController::class, 'getPluginUpdateFeed']);

Route::middleware('auth')->group(function () {
    Route::get('/plugin', [WppAdiFeedController::class, 'index']);
    Route::post('/plugin/upload', [WppAdiFeedController::class, 'upload']);
    Route::get('/profile', [ProfileController::class, 'edit'])->name('profile.edit');
    Route::patch('/profile', [ProfileController::class, 'update'])->name('profile.update');
    Route::delete('/profile', [ProfileController::class, 'destroy'])->name('profile.destroy');
    Route::get('/news-list/pdf', [NewsListController::class, 'createPDF']);
    Route::get('/news-list/excel/', [NewsListController::class, 'exportExecel']);

    Route::get('/news-list/clear', [NewsListController::class, 'clearFilter']);
    Route::resource('/news-list', NewsListController::class);

    Route::get('/configuration/feed-date-range', [ConfigurationController::class, 'feedDateRange'])->name('configuration.feed-date-range');
    Route::post('/configuration/track-feed-date-range', [ConfigurationController::class, 'trackDateRange'])->name('configuration.track-feed-date-range');
    Route::post('/configuration/store-feed-date-range', [ConfigurationController::class, 'storeFeedByDateRangeJob'])
    ->name('configuration.store-feed-date-range');

    Route::resource('/newspapers', NewspaperController::class);

    Route::post('/newspaper-tagurl/store', [NewspaperTagurlController::class, 'store'])->name('newspaper-tagurl.store');
    Route::delete('/newspaper-tagurl/destroy/{newspaperTagurl}', [NewspaperTagurlController::class, 'destroy'])->name('newspaper-tagurl.destroy');

    Route::get('/feed-news-list/clear', [FeedNewsListController::class, 'clearFilter'])->name('feed-news-list.filter');
    Route::post('/feed-news-list/pdf', [FeedNewsListController::class, 'createPDF'])->name('feed-news-list.pdf');
    Route::post('/feed-news-list/excel', [FeedNewsListController::class, 'exportExcel'])->name('feed-news-list.excel');
    Route::post('/feed-news-list/excel', [FeedNewsListController::class, 'exportExcel'])->name('feed-news-list.excel');

    Route::resource('/feed-news-list', FeedNewsListController::class);

    Route::get('tags/list', action: [TagController::class, 'list'])->name('tags.list');
    Route::resource('tags', TagController::class);
});

require __DIR__.'/auth.php';

app/Models/Tag.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Tag extends Model
{
    use HasFactory;
    protected $fillable = ['name', 'client',  'is_active'];
}

app/Http/Controllers/TagController.php
<?php

namespace App\Http\Controllers;

use App\Models\Tag;
use Illuminate\Http\Request;

class TagController extends Controller
{
    // Exibir a lista de tags
    public function index()
    {
        $tags = Tag::all();

        return view('tags.index', compact('tags'));
    }

    // Exibir o formulário de criação de tag
    public function create()
    {
        return view('tags.create');
    }

    // Exibir o formulário de edição de tag
    public function edit($id)
    {
        $tag = Tag::findOrFail($id);

        return view('tags.edit', compact('tag'));
    }

    public function show()
    {
    }

    // Salvar uma nova tag
    public function store(Request $request)
    {
        $request->validate([
            'name' => 'required|string|unique:tags,name|max:255',
        ]);

        Tag::create($request->all());

        return redirect()->route('tags.index');
    }

    // Atualizar uma tag existente
    public function update(Request $request, $id)
    {
        $tag = Tag::findOrFail($id);

        $request->validate([
            'name' => 'required|string|unique:tags,name,'.$tag->id.'|max:255',
        ]);

        $tag->update($request->all());

        return redirect()->route('tags.index');
    }

    // Deletar uma tag
    public function destroy($id)
    {
        $tag = Tag::findOrFail($id);

        // Alterna o estado de ativo/inativo
        $tag->is_active = !$tag->is_active;
        $tag->save();

        $status = $tag->is_active ? 'ativada' : 'desativada';

        return redirect()->route('tags.index')->with('success', "Tag {$status} com sucesso.");
    }

    public function list()
    {
        return Tag::where('is_active', true)->select('client', 'name')->get();
    }
}

app/View/Components/AppLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;
use Illuminate\View\View;

class AppLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     */
    public function render(): View
    {
        return view('layouts.app');
    }
}

resources/views/tags/create.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            {{ __('Tags') }}
        </h2>
    </x-slot>
    <div class="py-12">
    <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
        <div class="bg-white overflow-hidden shadow-sm sm:rounded-lg p-6">
            <h2 class="text-lg font-semibold text-gray-900 mb-4">Criar Tag</h2>

            <!-- Exibindo mensagens de erro -->
            @if ($errors->any())
                <div class="mb-4 p-4 bg-red-100 border-l-4 border-red-500 text-red-700 rounded-lg">
                    <strong>Erro!</strong> Verifique os seguintes problemas:
                    <ul class="mt-2 list-disc list-inside">
                        @foreach ($errors->all() as $error)
                            <li>{{ $error }}</li>
                        @endforeach
                    </ul>
                </div>
            @endif

            <form action="{{ route('tags.store') }}" method="POST" class="space-y-4">
                @csrf
                
                <!-- Nome da Tag -->
                <div>
                    <label for="name" class="block text-sm font-medium text-gray-700">Nome da Tag</label>
                    <input type="text" id="name" name="name" value="{{ old('name') }}" required
                           class="mt-1 block w-full rounded-lg border-gray-300 shadow-sm focus:ring-blue-500 focus:border-blue-500 p-2">
                </div>

                <!-- Nome do Cliente -->
                <div>
                    <label for="client" class="block text-sm font-medium text-gray-700">Nome do Cliente</label>
                    <input type="text" id="client" name="client" value="{{ old('client') }}" required
                           class="mt-1 block w-full rounded-lg border-gray-300 shadow-sm focus:ring-blue-500 focus:border-blue-500 p-2">
                </div>

                <!-- Botões -->
                <div class="flex space-x-4">
                    <button type="submit"
                            class="flex items-center justify-center px-4 py-2 bg-green-500 text-white font-semibold rounded-lg shadow-md hover:bg-green-600 transition duration-200">
                        <svg class="w-5 h-5 mr-2" fill="none" stroke="currentColor" stroke-width="2" viewBox="0 0 24 24"
                             xmlns="http://www.w3.org/2000/svg">
                            <path stroke-linecap="round" stroke-linejoin="round"
                                  d="M12 4v16m8-8H4"></path>
                        </svg>
                        Criar
                    </button>

                    <a href="{{ route('tags.index') }}"
                       class="flex items-center justify-center px-4 py-2 bg-gray-500 text-white font-semibold rounded-lg shadow-md hover:bg-gray-600 transition duration-200">
                        <svg class="w-5 h-5 mr-2" fill="none" stroke="currentColor" stroke-width="2" viewBox="0 0 24 24"
                             xmlns="http://www.w3.org/2000/svg">
                            <path stroke-linecap="round" stroke-linejoin="round"
                                  d="M10 19l-7-7m0 0l7-7m-7 7h18"></path>
                        </svg>
                        Voltar
                    </a>
                </div>
            </form>
        </div>
    </div>
</div>

</x-app-layout>

resources/views/tags/edit.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            {{ __('Tags') }}
        </h2>
    </x-slot>
    <div class="py-12">
    <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
        <div class="bg-white overflow-hidden shadow-sm sm:rounded-lg p-6">
            <h2 class="text-lg font-semibold text-gray-900 mb-4">Editar Tag</h2>

            <form action="{{ route('tags.update', $tag->id) }}" method="POST" class="space-y-4">
                @csrf
                @method('PUT')

                <!-- Nome da Tag -->
                <div>
                    <label for="name" class="block text-sm font-medium text-gray-700">Nome da Tag</label>
                    <input type="text" id="name" name="name" value="{{ $tag->name }}" required
                           class="mt-1 block w-full rounded-lg border-gray-300 shadow-sm focus:ring-blue-500 focus:border-blue-500 p-2">
                </div>

                <!-- Nome do Cliente -->
                <div>
                    <label for="client" class="block text-sm font-medium text-gray-700">Nome do Cliente</label>
                    <input type="text" id="client" name="client" value="{{ $tag->client }}" required
                           class="mt-1 block w-full rounded-lg border-gray-300 shadow-sm focus:ring-blue-500 focus:border-blue-500 p-2">
                </div>

                <!-- Botões de Ação -->
                <div class="flex space-x-4">
                    <button type="submit"
                            class="flex items-center justify-center px-4 py-2 bg-yellow-500 text-white font-semibold rounded-lg shadow-md hover:bg-yellow-600 transition duration-200">
                        <svg class="w-5 h-5 mr-2" fill="none" stroke="currentColor" stroke-width="2" viewBox="0 0 24 24"
                             xmlns="http://www.w3.org/2000/svg">
                            <path stroke-linecap="round" stroke-linejoin="round"
                                  d="M4 16l6 6M20 8l-6-6m0 0L4 16m16-8L10 2"></path>
                        </svg>
                        Atualizar
                    </button>

                    <a href="{{ route('tags.index') }}"
                       class="flex items-center justify-center px-4 py-2 bg-gray-500 text-white font-semibold rounded-lg shadow-md hover:bg-gray-600 transition duration-200">
                        <svg class="w-5 h-5 mr-2" fill="none" stroke="currentColor" stroke-width="2" viewBox="0 0 24 24"
                             xmlns="http://www.w3.org/2000/svg">
                            <path stroke-linecap="round" stroke-linejoin="round"
                                  d="M10 19l-7-7m0 0l7-7m-7 7h18"></path>
                        </svg>
                        Voltar
                    </a>
                    
                </div>
            </form>
        </div>
    </div>
</div>

</x-app-layout>

resources/views/tags/index.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            {{ __('Tags') }}
        </h2>
    </x-slot>
    <div class="py-12">
    <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
        <div class="bg-white overflow-hidden shadow-sm sm:rounded-lg p-6">
            <h2 class="text-lg font-semibold text-gray-900 mb-4">Gerenciar Tags</h2>

            <!-- Botão Criar Tag -->
            <a href="{{ route('tags.create') }}"
   class="inline-flex items-center px-4 py-2 bg-white text-blue-600 text-sm font-medium rounded-lg shadow-md hover:bg-gray-100 border border-blue-600 transition duration-200 mb-4">
    <svg class="w-5 h-5 mr-2 text-blue-600" fill="none" stroke="currentColor" stroke-width="2" viewBox="0 0 24 24"
         xmlns="http://www.w3.org/2000/svg">
        <path stroke-linecap="round" stroke-linejoin="round" d="M12 4v16m8-8H4"></path>
    </svg>
    Criar Tag
</a>


            <!-- Tabela -->
            <div class="overflow-x-auto bg-white rounded-lg shadow-md">
                <table class="min-w-full bg-white border border-gray-200">
                    <thead class="bg-gray-100 text-gray-700">
                        <tr>
                            <th class="px-4 py-2 text-left">ID</th>
                            <th class="px-4 py-2 text-left">Nome</th>
                            <th class="px-4 py-2 text-left">Cliente</th>
                            <th class="px-4 py-2 text-center">Ações</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach($tags as $tag)
                            <tr class="border-b">
                                <td class="px-4 py-2">{{ $tag->id }}</td>
                                <td class="px-4 py-2">{{ $tag->name }}</td>
                                <td class="px-4 py-2">{{ $tag->client }}</td>
                                <td class="px-4 py-2 flex justify-center space-x-2">
                                    <!-- Botão Editar -->
                                    <a href="{{ route('tags.edit', $tag->id) }}"
                                       class="px-3 py-1 bg-yellow-500 text-white text-sm rounded-lg shadow-md hover:bg-yellow-600 transition duration-200">
                                        Editar
                                    </a>

                                    <!-- Botão Ativar/Desativar -->
                                    <form action="{{ route('tags.destroy', $tag->id) }}" method="POST">
                                        @csrf
                                        @method('DELETE')
                                        <button type="submit"
                                                class="px-3 py-1 text-sm rounded-lg shadow-md transition duration-200
                                                {{ $tag->is_active ? 'bg-red-500 hover:bg-red-600 text-white' : 'bg-green-500 hover:bg-green-600 text-white' }}">
                                            {{ $tag->is_active ? 'Desativar' : 'Ativar' }}
                                        </button>
                                    </form>
                                </td>
                            </tr>
                        @endforeach
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
</x-app-layout>