routes/web.php
<?php

use App\Http\Controllers\ConfigurationController;
use App\Http\Controllers\FeedNewsListController;
use App\Http\Controllers\FeedReaderController;
use App\Http\Controllers\FeedWppAdiFeedController;
use App\Http\Controllers\NewsListController;
use App\Http\Controllers\NewspaperController;
use App\Http\Controllers\NewspaperTagurlController;
use App\Http\Controllers\ProfileController;
use App\Http\Controllers\TagController;
use App\Http\Controllers\WppAdiFeedController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

// Route::get('/', function () {
//     return view('welcome');
// });

Route::get('/', function () {
    return view('dashboard');
})->middleware(['auth', 'verified'])->name('dashboard');
Route::get('/dashboard', function () {
    return view('dashboard');
})->middleware(['auth', 'verified'])->name('dashboard');

Route::get('/feed-reader', [FeedReaderController::class, 'index']);
Route::get('/feed-update-news-stats', [FeedReaderController::class, 'updateNewsStats']);

Route::get('/feed-reader', [FeedReaderController::class, 'index']);
Route::post('/feed-wp-ativar', [FeedWppAdiFeedController::class, 'wpActive']);
Route::get('/wp-active-all-domain', [FeedWppAdiFeedController::class, 'wpActiveAllDomain']);
Route::get('/feed-job', [FeedWppAdiFeedController::class, 'index']);
Route::get('/feed-direct-url', [FeedWppAdiFeedController::class, 'feedDirectUrl']);

Route::get('/feed-wp-adi-plugin-update', [WppAdiFeedController::class, 'getPluginUpdateFeed']);

Route::middleware('auth')->group(function () {
    Route::get('/plugin', [WppAdiFeedController::class, 'index']);
    Route::post('/plugin/upload', [WppAdiFeedController::class, 'upload']);
    Route::get('/profile', [ProfileController::class, 'edit'])->name('profile.edit');
    Route::patch('/profile', [ProfileController::class, 'update'])->name('profile.update');
    Route::delete('/profile', [ProfileController::class, 'destroy'])->name('profile.destroy');
    Route::get('/news-list/pdf', [NewsListController::class, 'createPDF']);
    Route::get('/news-list/excel/', [NewsListController::class, 'exportExecel']);

    Route::get('/news-list/clear', [NewsListController::class, 'clearFilter']);
    Route::resource('/news-list', NewsListController::class);

    Route::get('/configuration/feed-date-range', [ConfigurationController::class, 'feedDateRange'])->name('configuration.feed-date-range');
    Route::post('/configuration/track-feed-date-range', [ConfigurationController::class, 'trackDateRange'])->name('configuration.track-feed-date-range');
    Route::post('/configuration/store-feed-date-range', [ConfigurationController::class, 'storeFeedByDateRangeJob'])
    ->name('configuration.store-feed-date-range');

    Route::resource('/newspapers', NewspaperController::class);

    Route::post('/newspaper-tagurl/store', [NewspaperTagurlController::class, 'store'])->name('newspaper-tagurl.store');
    Route::delete('/newspaper-tagurl/destroy/{newspaperTagurl}', [NewspaperTagurlController::class, 'destroy'])->name('newspaper-tagurl.destroy');

    Route::get('/feed-news-list/clear', [FeedNewsListController::class, 'clearFilter'])->name('feed-news-list.filter');
    Route::post('/feed-news-list/pdf', [FeedNewsListController::class, 'createPDF'])->name('feed-news-list.pdf');
    Route::post('/feed-news-list/excel', [FeedNewsListController::class, 'exportExcel'])->name('feed-news-list.excel');
    Route::post('/feed-news-list/excel', [FeedNewsListController::class, 'exportExcel'])->name('feed-news-list.excel');

    Route::resource('/feed-news-list', FeedNewsListController::class);

    Route::get('tags/list', action: [TagController::class, 'list'])->name('tags.list');
    Route::resource('tags', TagController::class);
});

require __DIR__.'/auth.php';

app/Models/Newspaper.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\HasMany;

class Newspaper extends Model
{
    use HasFactory;

    protected $fillable = [
        'newspaper_id',
        'wp_active',
        'wp_version',
        'tag',
        'url',
        'status',
        'tye_content',
        'name',
        'city',
        'id',
    ];

    public function FeedNewsList(): HasMany
    {
        return $this->hasMany(FeedNewsList::class);
    }

    public function tagUrl($tag = 'govpr')
    {
        return $this->hasMany(NewspaperTagurl::class, 'newspaper_id')->get(['id', 'tag', 'path'])->toArray();
    }
}

app/Http/Controllers/NewspaperController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\StoreNewspaperRequest;
use App\Http\Requests\UpdateNewspaperRequest;
use App\Models\Newspaper;
use App\Models\Tag;

class NewspaperController extends Controller
{
    /**
     * Display a listing of the resource.
     */
    public function index()
    {
        $newspapers = Newspaper::all();

        return view('newspapers.index', compact('newspapers'));
    }

    /**
     * Show the form for creating a new resource.
     */
    public function create()
    {
        return view('newspapers.add');
    }

    /**
     * Store a newly created resource in storage.
     */
    public function store(StoreNewspaperRequest $request)
    {
        $input = $request->all();

        $newspaper = new Newspaper();
        $newspaper->city = $input['city'];
        $newspaper->name = $input['name'];
        $url = rtrim($input['url'], '/');
        $newspaper->url = $url;
        $newspaper->type_content = $input['type_content'];
        $newspaper->save();

        return redirect()->route('newspapers.edit', $newspaper->id)->with('success', 'Jornal salvo com sucesso!');

        // return redirect()->route('newspapers.index')->with('success', 'Jornal salvo com sucesso!');
    }

    /**
     * Display the specified resource.
     */
    public function show(Newspaper $newspaper)
    {
    }

    /**
     * Show the form for editing the specified resource.
     */
    public function edit(Newspaper $newspaper)
    {
        $newspaper->tagurl = $newspaper->tagUrl();
        $action_icons = [
            'icon:trash | color:red | click:deleteTagurl({id})',
        ];

        $tagsList = Tag::where('is_active', true)->select('client', 'name')->get();

        return view('newspapers.edit', compact('newspaper', 'action_icons', 'tagsList'));
    }

    /**
     * Update the specified resource in storage.
     */
    public function update(UpdateNewspaperRequest $request, Newspaper $newspaper)
    {
        $input = $request->all();

        $newspaper->city = $input['city'];
        $newspaper->name = $input['name'];
        $url = rtrim($input['url'], '/');
        $newspaper->url = $url;
        $newspaper->type_content = $input['type_content'];
        $newspaper->save();

        return redirect()->route('newspapers.edit', $newspaper->id)->with('success', 'Jornal atualizado com sucesso!');

        // return redirect()->route('newspapers.index')->with('success', 'Jornal atualizado com sucesso!');
    }

    /**
     * Remove the specified resource from storage.
     */
    public function destroy(Newspaper $newspaper)
    {
        $newspaper->status = $newspaper->status == 'inativo' ? 'ativo' : 'inativo';
        $newspaper->save();

        return redirect()->route('newspapers.index')->with('success', 'Jornal Excluido com sucesso!');
    }
}

app/View/Components/AppLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;
use Illuminate\View\View;

class AppLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     */
    public function render(): View
    {
        return view('layouts.app');
    }
}

resources/views/newspapers/add.blade.php
<x-app-layout>
    <!-- Session Status -->
    <x-auth-session-status class="mb-4" :status="session('status')" />

    <div class="py-12">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            <div class="bg-white overflow-hidden shadow-sm sm:rounded-lg">

                <div class="p-6 text-gray-900">
                    <div class="block font-medium text-sm text-gray-700">

                        <form method="POST" action="{{ route('plugin.upload') }}" enctype="multipart/form-data" autocomplete="off">
                            @csrf

                            <!-- Arquivo do Plugin -->
                            <div class="mt-6 col-5">
                                <x-input-label for="plugin" :value="__('Arquivo do Plugin (ZIP)')" />
                                <x-text-input id="plugin" class="block mt-1 w-full" type="file" name="plugin" required />
                                <x-input-error :messages="$errors->get('plugin')" class="mt-2" />
                            </div>

                            <!-- Nome -->
                            <div class="mt-6 col-5">
                                <x-input-label for="name" :value="__('Nome do Plugin')" />
                                <x-text-input id="name" class="block mt-1 w-full" type="text" name="name" value="{{ old('name', $defaults['name']) }}" required />
                                <x-input-error :messages="$errors->get('name')" class="mt-2" />
                            </div>

                            <!-- Slug -->
                            <div class="mt-6 col-5">
                                <x-input-label for="slug" :value="__('Slug')" />
                                <x-text-input id="slug" class="block mt-1 w-full" type="text" name="slug" value="{{ old('slug', $defaults['slug']) }}" required />
                                <x-input-error :messages="$errors->get('slug')" class="mt-2" />
                            </div>

                            <!-- Versão -->
                            <div class="mt-6 col-5">
                                <x-input-label for="version" :value="__('Versão')" />
                                <x-text-input id="version" class="block mt-1 w-full" type="text" name="version" value="{{ old('version', $defaults['version']) }}" required />
                                <x-input-error :messages="$errors->get('version')" class="mt-2" />
                            </div>

                            <!-- Requer -->
                            <div class="mt-6 col-5">
                                <x-input-label for="requires" :value="__('Requer')" />
                                <x-text-input id="requires" class="block mt-1 w-full" type="text" name="requires" value="{{ old('requires', $defaults['requires']) }}" required />
                                <x-input-error :messages="$errors->get('requires')" class="mt-2" />
                            </div>

                            <!-- Testado com -->
                            <div class="mt-6 col-5">
                                <x-input-label for="tested" :value="__('Testado com')" />
                                <x-text-input id="tested" class="block mt-1 w-full" type="text" name="tested" value="{{ old('tested', $defaults['tested']) }}" required />
                                <x-input-error :messages="$errors->get('tested')" class="mt-2" />
                            </div>

                            <!-- Autor -->
                            <div class="mt-6 col-5">
                                <x-input-label for="author" :value="__('Autor')" />
                                <x-text-input id="author" class="block mt-1 w-full" type="text" name="author" value="{{ old('author', $defaults['author']) }}" required />
                                <x-input-error :messages="$errors->get('author')" class="mt-2" />
                            </div>

                            <!-- Homepage -->
                            <div class="mt-6 col-5">
                                <x-input-label for="homepage" :value="__('Homepage')" />
                                <x-text-input id="homepage" class="block mt-1 w-full" type="url" name="homepage" value="{{ old('homepage', $defaults['homepage']) }}" required />
                                <x-input-error :messages="$errors->get('homepage')" class="mt-2" />
                            </div>

                            <!-- Aviso de Atualização -->
                            <div class="mt-6 col-5">
                                <x-input-label for="upgrade_notice" :value="__('Aviso de Atualização')" />
                                <x-textarea id="upgrade_notice" class="block mt-1 w-full" name="upgrade_notice">{{ old('upgrade_notice', $defaults['upgrade_notice']) }}</x-textarea>
                                <x-input-error :messages="$errors->get('upgrade_notice')" class="mt-2" />
                            </div>

                            <!-- Botão de Enviar -->
                            <div class="flex items-center justify-end mt-4 col-5">
                                <x-primary-button class="ms-3">
                                    {{ __('Fazer Upload') }}
                                </x-primary-button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</x-app-layout>

resources/views/newspapers/edit.blade.php
<x-app-layout>
    <!-- Session Status -->
    <x-auth-session-status class="mb-4" :status="session('status')" />

    <div class="py-12">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            <div class="bg-white overflow-hidden shadow-sm sm:rounded-lg">
                @if (Session::has('success'))
                    <div class="max-w-7xl mx-auto  ">
                        <div class="alert alert-success">
                            {{ Session::get('success') }}
                        </div>
                    </div>
                @endif
                <div class="p-6 text-gray-900">
    <div class="block font-medium text-sm text-gray-700">
        <form method="POST" action="{{ route('newspapers.update', $newspaper->id) }}" class="grid grid-cols-1 sm:grid-cols-2 gap-6" autocomplete="off">
            @csrf
            @method('PUT')

            <!-- City -->
            <div class="input-group">
                <x-input-label for="city" :value="__('Cidade')" />
                <x-text-input id="city" class="block mt-1 w-full" type="text" name="city" value="{{$newspaper->city}}" />
                <x-input-error :messages="$errors->get('city')" class="mt-2" />
            </div>

            <!-- Name -->
            <div class="input-group">
                <x-input-label for="name" :value="__('Jornal')" />
                <x-text-input id="name" class="block mt-1 w-full" type="text" name="name" value="{{$newspaper->name}}" />
                <x-input-error :messages="$errors->get('name')" class="mt-2" />
            </div>

            <!-- URL -->
            <div class="input-group">
                <x-input-label for="url" :value="__('URL')" />
                <x-text-input id="url" class="block mt-1 w-full" type="text" name="url" value="{{$newspaper->url}}" />
                <x-input-error :messages="$errors->get('url')" class="mt-2" />
            </div>

            <!-- Type of Content -->
            <div class="input-group">
                <x-input-label for="type_content" :value="__('Tipo de Conteúdo')" />
                <x-text-input id="type_content" class="block mt-1 w-full" type="text" name="type_content" value="{{$newspaper->type_content}}" />
                <x-input-error :messages="$errors->get('type_content')" class="mt-2" />
            </div>

            <!-- Save Button -->
            <div class="flex items-center justify-end mt-4 col-span-2">
                <x-primary-button class="ms-3">
                    {{ __('Salvar') }}
                </x-primary-button>
            </div>
        </form>
    </div>
</div>

            </div>
        </div>
    </div>

    <div class="py-12">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            <div class="bg-white overflow-hidden shadow-sm sm:rounded-lg">
                <div class="p-6 text-gray-900">
                    <div class=" block font-medium text-sm text-gray-700 ">

                        <section class="space-y-6 ">
                            <header>
                                <h2 class="text-lg font-medium text-gray-900">
                                    FEEDs
                                </h2>
                                <p class="mt-1 text-sm text-gray-600">
                                    Lista de TAGS e Caminho do Feed (URL) vinculadas ao jornal
                                </p>
                            </header>

                            <div class="flex items-center justify-end mt-4  col-12">

                                <form id="add-tag-path-form">
                                    <!-- <x-text-input id="add-tag" name="tag" type="text" placeholder="{{ __('TAG') }}" autocomplete="off" /> -->


                                        <select name="tag" id="add-tag" class="block mt-1 w-full  select2"   autocomplete="off" >
                                            <option value="" disabled selected>Selecione uma Tag</option>
                                            @foreach($tagsList as $tag)
                                                <option value="{{ $tag['name'] }}">{{ $tag['name'] }} - {{ $tag['client'] }}</option>
                                            @endforeach
                                        </select>

                                    <x-text-input id="add-path" name="path" type="text" placeholder="{{ __('Path') }}"  autocomplete="off" />

                                    <x-primary-button size="small m-1">Adicionar TAG</x-primary-button>


                                    <x-input-error :messages="$errors->get('tag')" />
                                    <x-input-error :messages="$errors->get('path')" />

                                </form>
                            </div>



                        </section>
                        <x-bladewind::table compact="true" divider="thin" exclude_columns="id, marital_status"
                            data="{{ json_encode($newspaper['tagurl']) }}" :action_icons="$action_icons"
                            no_data_message=""></x-bladewind::table>
                    </div>
                </div>
            </div>
        </div>
    </div>


    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.js"></script>

    <script type="text/javascript">

        $.ajaxSetup({
            headers: {
                'X-CSRF-Token': '{{ csrf_token() }}'
            }
        });


        $('#add-tag-path-form').submit(function (event) {
            event.preventDefault();

            $.ajax({
                type: 'POST',
                url: '{{ route('newspaper-tagurl.store') }}',
                data: {
                    "newspaper_id": "{{ $newspaper->id }}",
                    "tag": $('#add-tag').val(),
                    "path": $('#add-path').val(),
                },
                dataType: 'json',
                success: function (response) {
                    $('#add-tag').val('')
                    $('#add-path').val('')
                    if (response.success) {
                        let data = response.data

                        let deleteHtml = `<td  class="text-right space-x-2 actions">
                            <button class="bw-button-circle tiny primary  !bg-red-500 hover:!bg-red-600 focus:ring-red-500 active:bg-red-600 focus:ring cursor-pointer rounded-full   has-icon" title = "" onclick = "deleteTagurl(${data.id})" href = "" type = "button" >
                            <svg class="size-6 inline-block stroke-2 !size-[18px]" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" aria-hidden="true">
                            <path stroke-linecap="round" stroke-linejoin="round" d="M14.74 9l-.346 9m-4.788 0L9.26 9m9.968-3.21c.342.052.682.107 1.022.166m-1.022-.165L18.16 19.673a2.25 2.25 0 01-2.244 2.077H8.084a2.25 2.25 0 01-2.244-2.077L4.772 5.79m14.456 0a48.108 48.108 0 00-3.478-.397m-12 .562c.34-.059.68-.114 1.022-.165m0 0a48.11 48.11 0 013.478-.397m7.5 0v-.916c0-1.18-.91-2.164-2.09-2.201a51.964 51.964 0 00-3.32 0c-1.18.037-2.09 1.022-2.09 2.201v.916m7.5 0a48.667 48.667 0 00-7.5 0"></path>
                            </svg><span class="grow "></span>
                                </button ></td>`;

                        $('.bw-table tbody').append(`<tr data-id="${data.id}"><td>${data.tag}</td><td>${data.path}</td>${deleteHtml}</tr>`);

                    } else {

                        alert(response.error);
                    }
                },
                error: function (xhr, status, error) {
                    // Handle the error
                    alert('Error: ' + error);
                }
            });
        });

        function deleteTagurl(id) {

            $.ajax({
                type: 'DELETE',
                url: '/newspaper-tagurl/destroy/' + id,
                data: { _token: '{{ csrf_token() }}' },
                success: function (response) {
                    if (response.success) {

                        $(`[data-id='${id}']`).remove()

                    } else {
                        alert(response.error);
                    }
                },
                error: function (xhr, status, error) {
                    // Handle the error
                    alert('Error: ' + error);
                }
            });

        }


    </script>


</x-app-layout>


<!-- Adicionar CSS do Select2 -->
<link href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.1.0-beta.1/css/select2.min.css" rel="stylesheet">
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/select2-bootstrap-5-theme@1.3.0/dist/select2-bootstrap-5-theme.min.css" />

<!-- Adicionar JS do Select2 -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.1.0-beta.1/js/select2.min.js"></script>
<script>
    $(document).ready(function () {
        $('#add-tag').select2({
            theme: 'bootstrap-5',
            placeholder: "Selecione ou digite uma Tag",
            allowClear: true // Adiciona opção de limpar o campo
        });
    });
</script>

resources/views/newspapers/index.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            {{ __('Newspapers') }}
        </h2>
    </x-slot>

    <div class="py-12">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8 p-6">
            <div class="bg-white overflow-hidden shadow-sm sm:rounded-lg">
                <div class="p-6 text-gray-900">
                    <!-- Botão Criar Portal com destaque -->
                    <a class="inline-flex items-center px-4 py-2 bg-blue-600 text-sm font-medium rounded-md shadow-md hover:bg-blue-700 focus:outline-none transition duration-200 mb-4" 
   href="{{ URL::to('/newspapers/create') }}">
    {{__('Adicionar um Portal')}}
</a>

                    <table class="table table-bordered mb-5">

                        {{ $line = null}}

                        <thead>
                            <tr>
                                <th scope="col">N</th>
                                <th scope="col">Cidade</th>
                                <th scope="col">Jornal</th>
                                <th scope="col">Portal</th>
                                <!-- <th scope="col">Tipo de Csonteúdo</th> -->
                                <th scope="col">WP</th>
                                <th scope="col">P.Versão</th>
                                <th scope="col"></th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach ($newspapers as $newspaper)

                            <tr class="{{ $loop->even ? 'bg-gray-50' : 'bg-white' }}">
                                <td>{{ $newspaper->id }}</td>
                                <td>{{ $newspaper->city }}</td>
                                <td>{{ $newspaper->name }}</td>
                                <td><a target="_blank" href="{{ $newspaper->url }}">{{ $newspaper->url }}</a></td>
                                <!-- <td>{{ $newspaper->type_content }}</td> -->
                                <td> 
                                    @if($newspaper->wp_active)
                                    <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="currentColor">
                                        <path fill="#ceb522" d="M12 2C6.5 2 2 6.5 2 12s4.5 10 10 10s10-4.5 10-10S17.5 2 12 2m-2 15l-5-5l1.41-1.41L10 14.17l7.59-7.59L19 8z"/>
                                    </svg>
                                    @endif
                                </td>
                                <td>{{$newspaper->wp_version}}</td>
                               
                                
                                <td class="flex items-center space-x-2">
    <!-- Botão de Editar -->
    <a class="inline-flex items-center px-3 py-2 border border-transparent text-sm leading-4 font-medium rounded-md text-gray-500 bg-white hover:text-gray-700 focus:outline-none transition ease-in-out duration-150" 
       href="/newspapers/{{$newspaper->id}}/edit">
        {{__('Editar')}}
    </a>

    <!-- Botão de Ativar/Desativar -->
    <form action="{{ route('newspapers.destroy',$newspaper->id) }}" method="POST" class="inline">
        @csrf
        @method('DELETE')
        <button type="submit" 
            class="inline-flex items-center px-3 py-2 border border-transparent text-sm leading-4 font-medium rounded-md text-white {{ $newspaper->status == 'inativo' ? 'bg-green-500 hover:bg-green-600' : 'bg-red-500 hover:bg-red-600' }} focus:outline-none transition ease-in-out duration-150">
            @if($newspaper->status == 'inativo')
                Ativar
            @else
                Desativar
            @endif
        </button>
    </form>
</td>

                            </tr>

                            @endforeach
                        </tbody>

                    </table>

                </div>
            </div>
        </div>
    </div>
</x-app-layout>