routes/web.php
<?php

use App\Http\Controllers\ConfigurationController;
use App\Http\Controllers\FeedNewsListController;
use App\Http\Controllers\FeedReaderController;
use App\Http\Controllers\FeedWppAdiFeedController;
use App\Http\Controllers\NewsListController;
use App\Http\Controllers\NewspaperController;
use App\Http\Controllers\NewspaperTagurlController;
use App\Http\Controllers\ProfileController;
use App\Http\Controllers\TagController;
use App\Http\Controllers\WppAdiFeedController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

// Route::get('/', function () {
//     return view('welcome');
// });

Route::get('/', function () {
    return view('dashboard');
})->middleware(['auth', 'verified'])->name('dashboard');
Route::get('/dashboard', function () {
    return view('dashboard');
})->middleware(['auth', 'verified'])->name('dashboard');

Route::get('/feed-reader', [FeedReaderController::class, 'index']);
Route::get('/feed-update-news-stats', [FeedReaderController::class, 'updateNewsStats']);

Route::get('/feed-reader', [FeedReaderController::class, 'index']);
Route::post('/feed-wp-ativar', [FeedWppAdiFeedController::class, 'wpActive']);
Route::get('/wp-active-all-domain', [FeedWppAdiFeedController::class, 'wpActiveAllDomain']);
Route::get('/feed-job', [FeedWppAdiFeedController::class, 'index']);
Route::get('/feed-direct-url', [FeedWppAdiFeedController::class, 'feedDirectUrl']);

Route::get('/feed-wp-adi-plugin-update', [WppAdiFeedController::class, 'getPluginUpdateFeed']);

Route::middleware('auth')->group(function () {
    Route::get('/plugin', [WppAdiFeedController::class, 'index']);
    Route::post('/plugin/upload', [WppAdiFeedController::class, 'upload']);
    Route::get('/profile', [ProfileController::class, 'edit'])->name('profile.edit');
    Route::patch('/profile', [ProfileController::class, 'update'])->name('profile.update');
    Route::delete('/profile', [ProfileController::class, 'destroy'])->name('profile.destroy');
    Route::get('/news-list/pdf', [NewsListController::class, 'createPDF']);
    Route::get('/news-list/excel/', [NewsListController::class, 'exportExecel']);

    Route::get('/news-list/clear', [NewsListController::class, 'clearFilter']);
    Route::resource('/news-list', NewsListController::class);

    Route::get('/configuration/feed-date-range', [ConfigurationController::class, 'feedDateRange'])->name('configuration.feed-date-range');
    Route::post('/configuration/track-feed-date-range', [ConfigurationController::class, 'trackDateRange'])->name('configuration.track-feed-date-range');
    Route::post('/configuration/store-feed-date-range', [ConfigurationController::class, 'storeFeedByDateRangeJob'])
    ->name('configuration.store-feed-date-range');

    Route::resource('/newspapers', NewspaperController::class);

    Route::post('/newspaper-tagurl/store', [NewspaperTagurlController::class, 'store'])->name('newspaper-tagurl.store');
    Route::delete('/newspaper-tagurl/destroy/{newspaperTagurl}', [NewspaperTagurlController::class, 'destroy'])->name('newspaper-tagurl.destroy');

    Route::get('/feed-news-list/clear', [FeedNewsListController::class, 'clearFilter'])->name('feed-news-list.filter');
    Route::post('/feed-news-list/pdf', [FeedNewsListController::class, 'createPDF'])->name('feed-news-list.pdf');
    Route::post('/feed-news-list/excel', [FeedNewsListController::class, 'exportExcel'])->name('feed-news-list.excel');
    Route::post('/feed-news-list/excel', [FeedNewsListController::class, 'exportExcel'])->name('feed-news-list.excel');

    Route::resource('/feed-news-list', FeedNewsListController::class);

    Route::get('tags/list', action: [TagController::class, 'list'])->name('tags.list');
    Route::resource('tags', TagController::class);
});

require __DIR__.'/auth.php';

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="csrf-token" content="{{ csrf_token() }}">
    <link rel="shortcut icon" href="{{ asset('images/favicon.png') }}">


    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Fonts -->
    <link rel="preconnect" href="https://fonts.bunny.net">
    <link href="https://fonts.bunny.net/css?family=figtree:400,500,600&display=swap" rel="stylesheet" />
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css">
    <!-----------------------------------------------------------
    -- animate.min.css by Daniel Eden (https://animate.style)
    -- is required for the animation of notifications and slide out panels
    -- you can ignore this step if you already have this file in your project
    --------------------------------------------------------------------------->
    <link href="{{ asset('vendor/bladewind/css/animate.min.css') }}" rel="stylesheet" />
    <link href="{{ asset('vendor/bladewind/css/bladewind-ui.min.css') }}" rel="stylesheet" />
    <!-- Scripts -->
    @vite(['resources/css/app.css', 'resources/js/app.js'])
    <script src="{{ asset('vendor/bladewind/js/helpers.js') }}"></script>
    <script src="//unpkg.com/alpinejs" defer></script>
</head>

<body class="font-sans antialiased">
    <div class="min-h-screen bg-gray-100">
        @include('layouts.navigation')

        <!-- Page Heading -->
        @if (isset($header))
            <header class="bg-white shadow">
                <div class="max-w-7xl mx-auto py-6 px-4 sm:px-6 lg:px-8">
                    {{ $header }}
                </div>
            </header>
        @endif

        <!-- Page Content -->
        <main>
            {{ $slot }}

        <!-- Botão fixo no canto inferior direito -->
        <div id="scrollToTop" class="fixed bottom-5 right-5 text-white rounded-full p-1 shadow-lg cursor-pointer transition-all hover:bg-blue-700 hidden ">
            <i class="fa fa-arrow-up"></i> <!-- Ícone de seta -->
            <svg xmlns="http://www.w3.org/2000/svg" width="36" height="36" viewBox="0 0 512 512"><path fill="#4cff19" d="M256 48a208 208 0 1 1 0 416a208 208 0 1 1 0-416m0 464a256 256 0 1 0 0-512a256 256 0 1 0 0 512M151.2 217.4c-4.6 4.2-7.2 10.1-7.2 16.4c0 12.3 10 22.3 22.3 22.3H208v96c0 17.7 14.3 32 32 32h32c17.7 0 32-14.3 32-32v-96h41.7c12.3 0 22.3-10 22.3-22.3c0-6.2-2.6-12.1-7.2-16.4l-91-84c-3.8-3.5-8.7-5.4-13.9-5.4s-10.1 1.9-13.9 5.4l-91 84z"/></svg>
        </div>
        </main>

<style>
    #scrollToTop{
        position: fixed;
        bottom: 1rem;
        right: 1rem;
    }

</style>
    <!-- Adicione o JavaScript para rolar até o topo -->
    <script>
        document.addEventListener('DOMContentLoaded', function () {
            const scrollToTopButton = document.getElementById('scrollToTop');
            // Quando o botão for clicado, rolar para o topo
            scrollToTopButton.addEventListener('click', function () {
                window.scrollTo({ top: 0, behavior: 'smooth' });
            });

            // Exibir ou esconder o botão com base no scroll da página
            window.addEventListener('scroll', function () {

                if (window.scrollY > 300) { // Defina um valor para aparecer
                    scrollToTopButton.classList.remove('hidden');

                } else {

                    scrollToTopButton.classList.add('hidden');
                }
            });
        });
    </script>
    </div>
</body>

</html>

resources/views/layouts/guest.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="csrf-token" content="{{ csrf_token() }}">

        <title>{{ config('app.name', 'Laravel') }}</title>

        <!-- Fonts -->
        <link rel="preconnect" href="https://fonts.bunny.net">
        <link href="https://fonts.bunny.net/css?family=figtree:400,500,600&display=swap" rel="stylesheet" />

        <!-- Scripts -->
        @vite(['resources/css/app.css', 'resources/js/app.js'])
    </head>
    <body class="font-sans text-gray-900 antialiased">
        <div class="min-h-screen flex flex-col sm:justify-center items-center pt-6 sm:pt-0 bg-gray-100">
            <div>
                <a href="/">
                   
                </a>
            </div>

            <div class="w-full sm:max-w-md mt-6 px-6 py-4 bg-white shadow-md overflow-hidden sm:rounded-lg">
                {{ $slot }}
            </div>
        </div>
    </body>
</html>

resources/views/layouts/navigation.blade.php
<nav x-data="{ open: false }" class="bg-white border-b border-gray-100">
    <!-- Primary Navigation Menu -->
    <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
        <div class="flex justify-between h-16">
            <div class="flex">
                <!-- Navigation Links -->
                <div class="hidden space-x-8 sm:-my-px sm:ms-10 sm:flex">
                    <x-nav-link :href="route('dashboard')" :active="request()->routeIs('dashboard')">
                        {{ __('Dashboard') }}
                    </x-nav-link>
                    <x-nav-link :href="route('newspapers.index')" :active="request()->routeIs('newspapers.index')">
                        {{ __('Newspapers') }}
                    </x-nav-link>
                </div>
            </div>

            <!-- Settings Dropdown -->
            <div class="hidden sm:flex sm:items-center sm:ms-6">
                <x-dropdown align="right" width="48">
                    <x-slot name="trigger">
                        <button class="inline-flex items-center px-3 py-2 border border-transparent text-sm leading-4 font-medium rounded-md text-gray-500 bg-white hover:text-gray-700 focus:outline-none transition ease-in-out duration-150">
                            <div>{{ Auth::user()->name }}</div>

                            <div class="ms-1">
                                <svg class="fill-current h-4 w-4" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20">
                                    <path fill-rule="evenodd" d="M5.293 7.293a1 1 0 011.414 0L10 10.586l3.293-3.293a1 1 0 111.414 1.414l-4 4a1 1 0 01-1.414 0l-4-4a1 1 0 010-1.414z" clip-rule="evenodd" />
                                </svg>
                            </div>
                        </button>
                    </x-slot>

                    <x-slot name="content">
                        <x-dropdown-link :href="route('profile.edit')">
                            {{ __('Profile') }}
                        </x-dropdown-link>

                        <!-- Authentication -->
                        <form method="POST" action="{{ route('logout') }}">
                            @csrf

                            <x-dropdown-link :href="route('logout')"
                                    onclick="event.preventDefault();
                                                this.closest('form').submit();">
                                {{ __('Log Out') }}
                            </x-dropdown-link>
                        </form>
                    </x-slot>
                </x-dropdown>
            </div>

            <!-- Hamburger -->
            <div class="-me-2 flex items-center sm:hidden">
                <button @click="open = ! open" class="inline-flex items-center justify-center p-2 rounded-md text-gray-400 hover:text-gray-500 hover:bg-gray-100 focus:outline-none focus:bg-gray-100 focus:text-gray-500 transition duration-150 ease-in-out">
                    <svg class="h-6 w-6" stroke="currentColor" fill="none" viewBox="0 0 24 24">
                        <path :class="{'hidden': open, 'inline-flex': ! open }" class="inline-flex" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 6h16M4 12h16M4 18h16" />
                        <path :class="{'hidden': ! open, 'inline-flex': open }" class="hidden" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12" />
                    </svg>
                </button>
            </div>
        </div>
    </div>

    <!-- Responsive Navigation Menu -->
    <div :class="{'block': open, 'hidden': ! open}" class="hidden sm:hidden">
        <div class="pt-2 pb-3 space-y-1">
            <x-responsive-nav-link :href="route('dashboard')" :active="request()->routeIs('dashboard')">
                {{ __('Dashboard') }}
            </x-responsive-nav-link>
        </div>

        <!-- Responsive Settings Options -->
        <div class="pt-4 pb-1 border-t border-gray-200">
            <div class="px-4">
                <div class="font-medium text-base text-gray-800">{{ Auth::user()->name }}</div>
                <div class="font-medium text-sm text-gray-500">{{ Auth::user()->email }}</div>
            </div>

            <div class="mt-3 space-y-1">
                <x-responsive-nav-link :href="route('profile.edit')">
                    {{ __('Profile') }}
                </x-responsive-nav-link>

                <!-- Authentication -->
                <form method="POST" action="{{ route('logout') }}">
                    @csrf

                    <x-responsive-nav-link :href="route('logout')"
                            onclick="event.preventDefault();
                                        this.closest('form').submit();">
                        {{ __('Log Out') }}
                    </x-responsive-nav-link>
                </form>
            </div>
        </div>
    </div>
</nav>